CREATE OR REPLACE VIEW DAILY_STATS_PROVINCE AS 
(
    SELECT CAST(DATE AS date) AS DATE, LOCATION_ISO_CODE, NEW_CASES, NEW_CASES_PER_MILLION, NEW_DEATHS, NEW_DEATHS_PER_MILLION, NEW_ACTIVE_CASES, NEW_RECOVERED, LOCATION, LOCATION_LEVEL
    FROM MAIN_TABLE_COVID
    WHERE LOCATION_LEVEL = 'Province'
    GROUP BY DATE, LOCATION_ISO_CODE, LOCATION, NEW_CASES, NEW_CASES_PER_MILLION, NEW_DEATHS, NEW_DEATHS_PER_MILLION, NEW_ACTIVE_CASES, NEW_RECOVERED, LOCATION_LEVEL 
    limit 20000
);
