CREATE OR REPLACE VIEW FACTORS AS 
(
    SELECT LOCATION_ISO_CODE, LOCATION, GROWTH_FACTOR_OF_NEW_DEATHS, NEW_DEATHS_PER_MILLION, CASE_FATALITY_RATE, CASE_RECOVERED_RATE,
    TOTAL_DEATHS_PER_MILLION, GROWTH_FACTOR_OF_NEW_CASES 
    FROM MAIN_TABLE_COVID
    GROUP BY LOCATION_ISO_CODE, LOCATION, GROWTH_FACTOR_OF_NEW_DEATHS, NEW_DEATHS_PER_MILLION, CASE_FATALITY_RATE, CASE_RECOVERED_RATE,
    TOTAL_DEATHS_PER_MILLION, GROWTH_FACTOR_OF_NEW_CASES  
    limit 20000
);
