CREATE OR REPLACE VIEW TOTAL_STATS AS 
(
    SELECT CAST(DATE AS date) AS DATE, YEAR(CAST(DATE AS date)) AS YEAR, MONTHNAME(CAST(DATE AS date)) AS MONTH,
    LOCATION_ISO_CODE, LOCATION, TOTAL_RECOVERED, TOTAL_CASES_PER_MILLION, TOTAL_RURAL_VILLAGES, TOTAL_REGENCIES,
    TOTAL_ACTIVE_CASES, TOTAL_CITIES, TOTAL_DISTRICTS, TOTAL_URBAN_VILLAGES, TOTAL_CASES, TOTAL_DEATHS, TOTAL_DEATHS_PER_MILLION, COUNTRY 
    FROM MAIN_TABLE_COVID
    GROUP BY DATE, YEAR, MONTH, LOCATION_ISO_CODE, LOCATION, TOTAL_RECOVERED, TOTAL_CASES_PER_MILLION, TOTAL_RURAL_VILLAGES, TOTAL_REGENCIES,
    TOTAL_ACTIVE_CASES, TOTAL_CITIES, TOTAL_DISTRICTS, TOTAL_URBAN_VILLAGES, TOTAL_CASES, TOTAL_DEATHS, TOTAL_DEATHS_PER_MILLION, COUNTRY  
    limit 20000
);
